#
# Author: Scott Ladd ( sladd@it.ucla.edu )
#

Description: >

    This stack contains the ECR repository which will hold the images for our
    built application. We allow any users associated with this account to push/push to/from this repository.

Parameters:

    RepositoryName:
        Description: The name of the ECR repository
        Type: String

Resources:

    Repository:
        Type: "AWS::ECR::Repository"
        Properties:
            RepositoryName: !Ref RepositoryName
            RepositoryPolicyText:
                Version: "2012-10-17"
                Statement:
                    -
                        Sid: AllowPushPull
                        Effect: Allow
                        Principal:
                            AWS:
                                !Ref AWS::AccountId
                        Action:
                            - "ecr:*"
                            - "ecr:GetAuthorizationToken"

Outputs:

    RepositoryArn:
        Value: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${Repository}

    RepositoryUri:
        Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}